/**
 * JP Pokemon TCG booster set reference prices.
 *
 * HKD prices:       sourced from price sheet (May 2026, HK market)
 * USD prices:       eBay sold-listing median (approx)
 * packMarketHKD:    boxMarketHKD ÷ packsPerBox (rounded)
 *
 * Series values (used for filter):
 *   "MEGA 系列" | "朱・紫系列" | "Sword & Shield 系列"
 */

export type BoosterSet = {
  id: string;
  nameJP: string;      // Japanese set name
  nameEN: string;      // English set name
  series: string;      // series label used by filters
  setCode: string;
  releaseDate: string; // YYYY-MM
  packsPerBox: number;
  packRetailJPY: number;
  boxRetailJPY: number;
  /** Secondary-market box price (USD) — eBay sold median */
  packMarketUSD: number;
  boxMarketUSD: number;
  /** HKD retail (suggested) */
  boxRetailHKD: number;
  /** HKD secondary-market box price */
  boxMarketHKD: number;
  /** HKD per-pack market price = Math.round(boxMarketHKD / packsPerBox) */
  packMarketHKD: number;
  emoji: string;
  popular?: boolean;
  /** Remote URL — pokemon-card.com hero image or pokemontcg.io logo */
  imageUrl?: string;
  /** Local require() asset from assets/card box/ */
  localImage?: any;
  fallbackImageUrl?: string;
  pricechartingId?: string | null;
  ebayUrl: string;
};

// ─── Local image map (static require — paths must be string literals) ─────────
const img = {
  M1L:   require('../assets/card box/M1L.jpg'),
  M1S:   require('../assets/card box/M1S.jpg'),
  M2:    require('../assets/card box/M2.jpg'),
  M2a:   require('../assets/card box/M2a.jpg'),
  M3:    require('../assets/card box/M3.jpg'),
  M4:    require('../assets/card box/M4.jpg'),
  M5:    require('../assets/card box/M5.jpg'),
  SV1:   require('../assets/card box/SV1.jpg'),
  SV1V:  require('../assets/card box/SV1V.jpg'),
  // SV1a missing — no local asset
  SV2:   require('../assets/card box/SV2.jpg'),
  SV2P:  require('../assets/card box/SV2P.jpg'),
  SV2a:  require('../assets/card box/SV2a.jpg'),
  SV3:   require('../assets/card box/SV3.jpg'),
  SV3a:  require('../assets/card box/SV3a.jpg'),
  SV4:   require('../assets/card box/SV4.jpg'),
  SV4K:  require('../assets/card box/SV4K.jpg'),
  SV4a:  require('../assets/card box/SV4a.jpg'),
  SV5K:  require('../assets/card box/SV5K.jpg'),
  SV5M:  require('../assets/card box/SV5M.jpg'),
  // SV5a missing — no local asset
  SV6:   require('../assets/card box/SV6.jpg'),
  SV6a:  require('../assets/card box/SV6a.jpg'),
  SV7:   require('../assets/card box/SV7.jpg'),
  SV8:   require('../assets/card box/sv8.jpg'),
  SV8a:  require('../assets/card box/sv8a.jpg'),
  SV9:   require('../assets/card box/sv9.jpg'),
  SV9a:  require('../assets/card box/sv9a.jpg'),
  SV10:  require('../assets/card box/SV10.jpg'),
  SV11B: require('../assets/card box/SV11B.jpg'),
  SV11W: require('../assets/card box/SV11W.jpg'),
  S1W:   require('../assets/card box/S1W.jpg'),
  S1H:   require('../assets/card box/S1H.jpg'),
  S2:    require('../assets/card box/S2.jpg'),
  S3:    require('../assets/card box/S3.jpg'),
  S4:    require('../assets/card box/S4.jpg'),
  S5R:   require('../assets/card box/S5R.jpg'),
  S5I:   require('../assets/card box/S5I.jpg'),
  S6a:   require('../assets/card box/S6a.jpg'),
  S7R:   require('../assets/card box/S7R.jpg'),
  S7D:   require('../assets/card box/S7D.jpg'),
  S8:    require('../assets/card box/S8.jpg'),
  S8b:   require('../assets/card box/S8b.jpg'),
  S9:    require('../assets/card box/S9.jpg'),
  S9a:   require('../assets/card box/S9a.jpg'),
  S10a:  require('../assets/card box/S10a.jpg'),
  S10b:  require('../assets/card box/S10b.jpg'),
  S11:   require('../assets/card box/S11.jpg'),
  S12:   require('../assets/card box/S12.jpg'),
  S12a:  require('../assets/card box/S12a.jpg'),
  SP:    require('../assets/card box/SP.jpg'),
};

// ─── URL helpers ──────────────────────────────────────────────────────────────
const packImg = (setId: string) =>
  `https://asia.pokemon-card.com/id/archive/special/card/${setId}/assets/images/hero-pack.png`;

const tcgLogo = (setId: string) =>
  `https://images.pokemontcg.io/${setId}/logo.png`;

const ebay = (q: string) =>
  `https://www.ebay.com/sch/i.html?_nkw=${encodeURIComponent(q)}&LH_Complete=1&LH_Sold=1&_sop=16`;

// ─── Data ─────────────────────────────────────────────────────────────────────

export const BOOSTER_SETS: BoosterSet[] = [

  // ══════════════════════════════════════════════════════════════════════════════
  // MEGA 系列 (2025–2026)
  // ══════════════════════════════════════════════════════════════════════════════
  {
    id: 'm1l',
    nameJP: 'メガブレイブ',
    nameEN: 'Mega Brave',
    series: 'MEGA 系列',
    setCode: 'M1L',
    releaseDate: '2025-04',
    packsPerBox: 30,
    packRetailJPY: 180,
    boxRetailJPY: 5400,
    packMarketUSD: 3.6,
    boxMarketUSD: 109,
    boxRetailHKD: 280,
    boxMarketHKD: 850,
    packMarketHKD: 28,
    emoji: '💪',
    popular: true,
    localImage: img.M1L,
    fallbackImageUrl: tcgLogo('sv8'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese mega brave M1L booster box sealed'),
  },
  {
    id: 'm1s',
    nameJP: 'メガシンフォニア',
    nameEN: 'Mega Symphonia',
    series: 'MEGA 系列',
    setCode: 'M1S',
    releaseDate: '2025-04',
    packsPerBox: 30,
    packRetailJPY: 180,
    boxRetailJPY: 5400,
    packMarketUSD: 3.9,
    boxMarketUSD: 119,
    boxRetailHKD: 280,
    boxMarketHKD: 924,
    packMarketHKD: 31,
    emoji: '🎵',
    localImage: img.M1S,
    fallbackImageUrl: tcgLogo('sv8'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese mega symphonia M1S booster box sealed'),
  },
  {
    id: 'm2',
    nameJP: 'インフェルノX',
    nameEN: 'Inferno X',
    series: 'MEGA 系列',
    setCode: 'M2',
    releaseDate: '2025-06',
    packsPerBox: 30,
    packRetailJPY: 180,
    boxRetailJPY: 5400,
    packMarketUSD: 5.3,
    boxMarketUSD: 160,
    boxRetailHKD: 280,
    boxMarketHKD: 1250,
    packMarketHKD: 42,
    emoji: '🔥',
    popular: true,
    localImage: img.M2,
    fallbackImageUrl: tcgLogo('sv8'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese inferno X M2 booster box sealed'),
  },
  {
    id: 'm2a',
    nameJP: 'MEGAドリームex',
    nameEN: 'MEGA Dream ex',
    series: 'MEGA 系列',
    setCode: 'M2a',
    releaseDate: '2025-07',
    packsPerBox: 30,
    packRetailJPY: 310,
    boxRetailJPY: 9300,
    packMarketUSD: 3.6,
    boxMarketUSD: 109,
    boxRetailHKD: 310,
    boxMarketHKD: 850,
    packMarketHKD: 28,
    emoji: '✨',
    localImage: img.M2a,
    fallbackImageUrl: tcgLogo('sv8'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese MEGA dream ex M2a booster box sealed'),
  },
  {
    id: 'm3',
    nameJP: 'ニルの虚空',
    nameEN: 'Nihil Zero',
    series: 'MEGA 系列',
    setCode: 'M3',
    releaseDate: '2025-09',
    packsPerBox: 30,
    packRetailJPY: 310,
    boxRetailJPY: 9300,
    packMarketUSD: 3.0,
    boxMarketUSD: 90,
    boxRetailHKD: 310,
    boxMarketHKD: 700,
    packMarketHKD: 23,
    emoji: '🌑',
    localImage: img.M3,
    fallbackImageUrl: tcgLogo('sv8'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese nihil zero M3 booster box sealed'),
  },
  {
    id: 'm4',
    nameJP: 'ニンジャスピナー',
    nameEN: 'Ninja Spinner',
    series: 'MEGA 系列',
    setCode: 'M4',
    releaseDate: '2025-11',
    packsPerBox: 30,
    packRetailJPY: 310,
    boxRetailJPY: 9300,
    packMarketUSD: 3.0,
    boxMarketUSD: 90,
    boxRetailHKD: 310,
    boxMarketHKD: 700,
    packMarketHKD: 23,
    emoji: '🥷',
    localImage: img.M4,
    fallbackImageUrl: tcgLogo('sv8'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese ninja spinner M4 booster box sealed'),
  },
  {
    id: 'm5',
    nameJP: 'アビスアイ',
    nameEN: 'Abyss Eye',
    series: 'MEGA 系列',
    setCode: 'M5',
    releaseDate: '2026-01',
    packsPerBox: 30,
    packRetailJPY: 310,
    boxRetailJPY: 9300,
    packMarketUSD: 2.9,
    boxMarketUSD: 87,
    boxRetailHKD: 310,
    boxMarketHKD: 680,
    packMarketHKD: 23,
    emoji: '👁️',
    localImage: img.M5,
    fallbackImageUrl: tcgLogo('sv8'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese abyss eye M5 booster box sealed'),
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // 朱・紫系列  Scarlet & Violet (2023–2026)
  // ══════════════════════════════════════════════════════════════════════════════
  {
    id: 'sv1',
    nameJP: 'スカーレットex',
    nameEN: 'Scarlet ex',
    series: '朱・紫系列',
    setCode: 'SV1',
    releaseDate: '2023-01',
    packsPerBox: 30,
    packRetailJPY: 180,
    boxRetailJPY: 5400,
    packMarketUSD: 2.5,
    boxMarketUSD: 96,
    boxRetailHKD: 280,
    boxMarketHKD: 750,
    packMarketHKD: 25,
    emoji: '🔴',
    localImage: img.SV1,
    fallbackImageUrl: tcgLogo('sv1'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese scarlet ex sv1 booster box sealed'),
  },
  {
    id: 'sv1v',
    nameJP: 'バイオレットex',
    nameEN: 'Violet ex',
    series: '朱・紫系列',
    setCode: 'SV1V',
    releaseDate: '2023-01',
    packsPerBox: 30,
    packRetailJPY: 180,
    boxRetailJPY: 5400,
    packMarketUSD: 4.3,
    boxMarketUSD: 167,
    boxRetailHKD: 280,
    boxMarketHKD: 1300,
    packMarketHKD: 43,
    emoji: '🟣',
    popular: true,
    localImage: img.SV1V,
    fallbackImageUrl: tcgLogo('sv1'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese violet ex sv1v booster box sealed'),
  },
  {
    id: 'sv1a',
    nameJP: 'トリプレットビート',
    nameEN: 'Triplet Beat',
    series: '朱・紫系列',
    setCode: 'SV1a',
    releaseDate: '2023-03',
    packsPerBox: 30,
    packRetailJPY: 180,
    boxRetailJPY: 5400,
    packMarketUSD: 4.3,
    boxMarketUSD: 167,
    boxRetailHKD: 280,
    boxMarketHKD: 1300,
    packMarketHKD: 43,
    emoji: '🎵',
    popular: true,
    imageUrl: packImg('sv1a'),
    fallbackImageUrl: tcgLogo('sv1'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese triplet beat sv1a booster box sealed'),
  },
  {
    id: 'sv2',
    nameJP: 'クレイバースト',
    nameEN: 'Clay Burst',
    series: '朱・紫系列',
    setCode: 'SV2',
    releaseDate: '2023-04',
    packsPerBox: 30,
    packRetailJPY: 180,
    boxRetailJPY: 5400,
    packMarketUSD: 2.7,
    boxMarketUSD: 103,
    boxRetailHKD: 280,
    boxMarketHKD: 800,
    packMarketHKD: 27,
    emoji: '💥',
    localImage: img.SV2,
    fallbackImageUrl: tcgLogo('sv2'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese clay burst sv2 booster box sealed'),
  },
  {
    id: 'sv2p',
    nameJP: 'スノーハザード',
    nameEN: 'Snow Hazard',
    series: '朱・紫系列',
    setCode: 'SV2P',
    releaseDate: '2023-04',
    packsPerBox: 30,
    packRetailJPY: 180,
    boxRetailJPY: 5400,
    packMarketUSD: 1.6,
    boxMarketUSD: 62,
    boxRetailHKD: 280,
    boxMarketHKD: 480,
    packMarketHKD: 16,
    emoji: '❄️',
    localImage: img.SV2P,
    fallbackImageUrl: tcgLogo('sv2'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese snow hazard sv2p booster box sealed'),
  },
  {
    id: 'sv2a',
    nameJP: 'ポケモンカード151',
    nameEN: 'Pokemon Card 151',
    series: '朱・紫系列',
    setCode: 'SV2a',
    releaseDate: '2023-06',
    packsPerBox: 20,
    packRetailJPY: 440,
    boxRetailJPY: 8800,
    packMarketUSD: 185.0,   // HKD 3700 / 20 packs / 7.8
    boxMarketUSD: 474,
    boxRetailHKD: 300,
    boxMarketHKD: 3700,
    packMarketHKD: 185,
    emoji: '😺',
    popular: true,
    localImage: img.SV2a,
    fallbackImageUrl: tcgLogo('mew'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese 151 booster box sv2a sealed'),
  },
  {
    id: 'sv3',
    nameJP: '黒炎の支配者',
    nameEN: 'Ruler of Black Flame',
    series: '朱・紫系列',
    setCode: 'SV3',
    releaseDate: '2023-07',
    packsPerBox: 30,
    packRetailJPY: 180,
    boxRetailJPY: 5400,
    packMarketUSD: 1.8,
    boxMarketUSD: 71,
    boxRetailHKD: 280,
    boxMarketHKD: 550,
    packMarketHKD: 18,
    emoji: '🐉',
    popular: true,
    localImage: img.SV3,
    fallbackImageUrl: tcgLogo('sv3'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese ruler black flame sv3 booster box sealed'),
  },
  {
    id: 'sv3a',
    nameJP: 'レイジングサーフ',
    nameEN: 'Raging Surf',
    series: '朱・紫系列',
    setCode: 'SV3a',
    releaseDate: '2023-09',
    packsPerBox: 30,
    packRetailJPY: 180,
    boxRetailJPY: 5400,
    packMarketUSD: 2.2,
    boxMarketUSD: 83,
    boxRetailHKD: 280,
    boxMarketHKD: 650,
    packMarketHKD: 22,
    emoji: '🌊',
    popular: true,
    localImage: img.SV3a,
    fallbackImageUrl: tcgLogo('sv3'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese raging surf sv3a booster box sealed'),
  },
  {
    id: 'sv4',
    nameJP: '古代の咆哮',
    nameEN: 'Ancient Roar',
    series: '朱・紫系列',
    setCode: 'SV4',
    releaseDate: '2023-10',
    packsPerBox: 30,
    packRetailJPY: 180,
    boxRetailJPY: 5400,
    packMarketUSD: 1.5,
    boxMarketUSD: 56,
    boxRetailHKD: 280,
    boxMarketHKD: 440,
    packMarketHKD: 15,
    emoji: '🦕',
    localImage: img.SV4,
    fallbackImageUrl: tcgLogo('sv4'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese ancient roar sv4 booster box sealed'),
  },
  {
    id: 'sv4k',
    nameJP: '未来の一閃',
    nameEN: 'Future Flash',
    series: '朱・紫系列',
    setCode: 'SV4K',
    releaseDate: '2023-10',
    packsPerBox: 30,
    packRetailJPY: 180,
    boxRetailJPY: 5400,
    packMarketUSD: 1.5,
    boxMarketUSD: 56,
    boxRetailHKD: 280,
    boxMarketHKD: 440,
    packMarketHKD: 15,
    emoji: '⚡',
    localImage: img.SV4K,
    fallbackImageUrl: tcgLogo('sv4'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese future flash sv4k booster box sealed'),
  },
  {
    id: 'sv4a',
    nameJP: 'シャイニートレジャーex',
    nameEN: 'Shiny Treasure ex',
    series: '朱・紫系列',
    setCode: 'SV4a',
    releaseDate: '2023-12',
    packsPerBox: 10,          // high-class pack: 10 packs/box
    packRetailJPY: 800,
    boxRetailJPY: 8000,
    packMarketUSD: 5.8,
    boxMarketUSD: 58,
    boxRetailHKD: 280,
    boxMarketHKD: 450,
    packMarketHKD: 45,        // 450 ÷ 10
    emoji: '💎',
    popular: true,
    localImage: img.SV4a,
    fallbackImageUrl: tcgLogo('sv4'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese shiny treasure ex sv4a booster box sealed'),
  },
  {
    id: 'sv5k',
    nameJP: 'ワイルドフォース',
    nameEN: 'Wild Force',
    series: '朱・紫系列',
    setCode: 'SV5K',
    releaseDate: '2024-01',
    packsPerBox: 30,
    packRetailJPY: 180,
    boxRetailJPY: 5400,
    packMarketUSD: 1.5,
    boxMarketUSD: 58,
    boxRetailHKD: 280,
    boxMarketHKD: 450,
    packMarketHKD: 15,
    emoji: '🦁',
    localImage: img.SV5K,
    fallbackImageUrl: tcgLogo('sv5'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese wild force sv5k booster box sealed'),
  },
  {
    id: 'sv5m',
    nameJP: 'サイバージャッジ',
    nameEN: 'Cyber Judge',
    series: '朱・紫系列',
    setCode: 'SV5M',
    releaseDate: '2024-01',
    packsPerBox: 30,
    packRetailJPY: 180,
    boxRetailJPY: 5400,
    packMarketUSD: 1.5,
    boxMarketUSD: 58,
    boxRetailHKD: 280,
    boxMarketHKD: 450,
    packMarketHKD: 15,
    emoji: '🤖',
    localImage: img.SV5M,
    fallbackImageUrl: tcgLogo('sv5'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese cyber judge sv5m booster box sealed'),
  },
  {
    id: 'sv5a',
    nameJP: '変幻の仮面',
    nameEN: 'Mask of Change',
    series: '朱・紫系列',
    setCode: 'SV5a',
    releaseDate: '2024-04',
    packsPerBox: 30,
    packRetailJPY: 180,
    boxRetailJPY: 5400,
    packMarketUSD: 1.5,
    boxMarketUSD: 58,
    boxRetailHKD: 280,
    boxMarketHKD: 450,
    packMarketHKD: 15,
    emoji: '🎭',
    imageUrl: packImg('sv5a'),       // no local asset for sv5a
    fallbackImageUrl: tcgLogo('sv5'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese mask of change sv5a booster box sealed'),
  },
  {
    id: 'sv6',
    nameJP: 'ステラミラクル',
    nameEN: 'Stellar Miracle',
    series: '朱・紫系列',
    setCode: 'SV6',
    releaseDate: '2024-07',
    packsPerBox: 30,
    packRetailJPY: 180,
    boxRetailJPY: 5400,
    packMarketUSD: 1.5,
    boxMarketUSD: 58,
    boxRetailHKD: 280,
    boxMarketHKD: 450,
    packMarketHKD: 15,
    emoji: '✨',
    localImage: img.SV6,
    fallbackImageUrl: tcgLogo('sv6'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese stellar miracle sv6 booster box sealed'),
  },
  {
    id: 'sv6a',
    nameJP: 'ナイトワンダラー',
    nameEN: 'Night Wanderer',
    series: '朱・紫系列',
    setCode: 'SV6a',
    releaseDate: '2024-06',
    packsPerBox: 30,
    packRetailJPY: 180,
    boxRetailJPY: 5400,
    packMarketUSD: 1.6,
    boxMarketUSD: 62,
    boxRetailHKD: 280,
    boxMarketHKD: 480,
    packMarketHKD: 16,
    emoji: '🌙',
    localImage: img.SV6a,
    fallbackImageUrl: tcgLogo('sv6'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese night wanderer sv6a booster box sealed'),
  },
  {
    id: 'sv7',
    nameJP: '楽園ドラゴーナ',
    nameEN: 'Paradise Dragona',
    series: '朱・紫系列',
    setCode: 'SV7',
    releaseDate: '2024-10',
    packsPerBox: 30,
    packRetailJPY: 180,
    boxRetailJPY: 5400,
    packMarketUSD: 2.7,
    boxMarketUSD: 103,
    boxRetailHKD: 280,
    boxMarketHKD: 800,
    packMarketHKD: 27,
    emoji: '🐲',
    popular: true,
    localImage: img.SV7,
    fallbackImageUrl: tcgLogo('sv7'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese paradise dragona sv7 booster box sealed'),
  },
  {
    id: 'sv8',
    nameJP: '超電磁ストーム',
    nameEN: 'Super Electric Breaker',
    series: '朱・紫系列',
    setCode: 'SV8',
    releaseDate: '2024-12',
    packsPerBox: 30,
    packRetailJPY: 180,
    boxRetailJPY: 5400,
    packMarketUSD: 2.8,
    boxMarketUSD: 109,
    boxRetailHKD: 280,
    boxMarketHKD: 850,
    packMarketHKD: 28,
    emoji: '⚡',
    localImage: img.SV8,
    fallbackImageUrl: tcgLogo('sv8'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese super electric breaker sv8 booster box sealed'),
  },
  {
    id: 'sv8a',
    nameJP: 'バトルパートナーズ',
    nameEN: 'Battle Partners',
    series: '朱・紫系列',
    setCode: 'SV8a',
    releaseDate: '2025-02',
    packsPerBox: 30,
    packRetailJPY: 310,
    boxRetailJPY: 9300,
    packMarketUSD: 4.7,
    boxMarketUSD: 179,
    boxRetailHKD: 310,
    boxMarketHKD: 1400,
    packMarketHKD: 47,
    emoji: '🤝',
    popular: true,
    localImage: img.SV8a,
    fallbackImageUrl: tcgLogo('sv8'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese battle partners sv8a booster box sealed'),
  },
  {
    id: 'sv9a',
    nameJP: '熱風競技場',
    nameEN: 'Hot Air Arena',
    series: '朱・紫系列',
    setCode: 'SV9a',
    releaseDate: '2025-04',
    packsPerBox: 30,
    packRetailJPY: 310,
    boxRetailJPY: 9300,
    packMarketUSD: 2.7,
    boxMarketUSD: 103,
    boxRetailHKD: 310,
    boxMarketHKD: 800,
    packMarketHKD: 27,
    emoji: '🔥',
    localImage: img.SV9a,
    fallbackImageUrl: tcgLogo('sv8'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese hot air arena sv9a booster box sealed'),
  },
  {
    id: 'sv9',
    nameJP: '對戰搭檔',
    nameEN: 'Battle Partners',
    series: '朱・紫系列',
    setCode: 'SV9',
    releaseDate: '2025-06',
    packsPerBox: 30,
    packRetailJPY: 310,
    boxRetailJPY: 9300,
    packMarketUSD: 2.7,
    boxMarketUSD: 103,
    boxRetailHKD: 310,
    boxMarketHKD: 800,
    packMarketHKD: 27,
    emoji: '🎮',
    localImage: img.SV9,
    fallbackImageUrl: tcgLogo('sv8'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese sv9 booster box sealed'),
  },
  {
    id: 'sv10',
    nameJP: '緋紅薄霧',
    nameEN: 'Crimson Haze',
    series: '朱・紫系列',
    setCode: 'SV10',
    releaseDate: '2025-08',
    packsPerBox: 30,
    packRetailJPY: 310,
    boxRetailJPY: 9300,
    packMarketUSD: 6.0,
    boxMarketUSD: 231,
    boxRetailHKD: 310,
    boxMarketHKD: 1800,
    packMarketHKD: 60,
    emoji: '🌫️',
    popular: true,
    localImage: img.SV10,
    fallbackImageUrl: tcgLogo('sv8'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese sv10 crimson haze booster box sealed'),
  },
  {
    id: 'sv11b',
    nameJP: 'ブラックボルト',
    nameEN: 'Black Bolt',
    series: '朱・紫系列',
    setCode: 'SV11B',
    releaseDate: '2026-01',
    packsPerBox: 30,
    packRetailJPY: 310,
    boxRetailJPY: 9300,
    packMarketUSD: 5.0,
    boxMarketUSD: 192,
    boxRetailHKD: 310,
    boxMarketHKD: 1500,
    packMarketHKD: 50,
    emoji: '⚫',
    popular: true,
    localImage: img.SV11B,
    fallbackImageUrl: tcgLogo('sv8'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese black bolt sv11b booster box sealed'),
  },
  {
    id: 'sv11w',
    nameJP: 'ホワイトフレア',
    nameEN: 'White Flare',
    series: '朱・紫系列',
    setCode: 'SV11W',
    releaseDate: '2026-01',
    packsPerBox: 30,
    packRetailJPY: 310,
    boxRetailJPY: 9300,
    packMarketUSD: 5.0,
    boxMarketUSD: 192,
    boxRetailHKD: 310,
    boxMarketHKD: 1500,
    packMarketHKD: 50,
    emoji: '⚪',
    popular: true,
    localImage: img.SV11W,
    fallbackImageUrl: tcgLogo('sv8'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese white flare sv11w booster box sealed'),
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // Sword & Shield 系列 (2020–2022)
  // ══════════════════════════════════════════════════════════════════════════════
  {
    id: 's1w',
    nameJP: 'ソード',
    nameEN: 'Sword',
    series: 'Sword & Shield 系列',
    setCode: 'S1W',
    releaseDate: '2020-01',
    packsPerBox: 30,
    packRetailJPY: 165,
    boxRetailJPY: 4950,
    packMarketUSD: 27.8,
    boxMarketUSD: 833,
    boxRetailHKD: 260,
    boxMarketHKD: 6500,
    packMarketHKD: 217,
    emoji: '⚔️',
    popular: true,
    localImage: img.S1W,
    fallbackImageUrl: tcgLogo('swsh1'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese sword s1w booster box sealed'),
  },
  {
    id: 's1h',
    nameJP: 'シールド',
    nameEN: 'Shield',
    series: 'Sword & Shield 系列',
    setCode: 'S1H',
    releaseDate: '2020-01',
    packsPerBox: 30,
    packRetailJPY: 165,
    boxRetailJPY: 4950,
    packMarketUSD: 27.8,
    boxMarketUSD: 833,
    boxRetailHKD: 260,
    boxMarketHKD: 6500,
    packMarketHKD: 217,
    emoji: '🛡️',
    popular: true,
    localImage: img.S1H,
    fallbackImageUrl: tcgLogo('swsh1'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese shield s1h booster box sealed'),
  },
  {
    id: 's2',
    nameJP: '反乱クラッシュ',
    nameEN: 'Rebellion Crash',
    series: 'Sword & Shield 系列',
    setCode: 'S2',
    releaseDate: '2020-06',
    packsPerBox: 30,
    packRetailJPY: 165,
    boxRetailJPY: 4950,
    packMarketUSD: 19.2,
    boxMarketUSD: 577,
    boxRetailHKD: 260,
    boxMarketHKD: 4500,
    packMarketHKD: 150,
    emoji: '💢',
    localImage: img.S2,
    fallbackImageUrl: tcgLogo('swsh2'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese rebellion crash s2 booster box sealed'),
  },
  {
    id: 's3',
    nameJP: '無限ゾーン',
    nameEN: 'Infinite Zone',
    series: 'Sword & Shield 系列',
    setCode: 'S3',
    releaseDate: '2020-09',
    packsPerBox: 30,
    packRetailJPY: 165,
    boxRetailJPY: 4950,
    packMarketUSD: 17.3,
    boxMarketUSD: 526,
    boxRetailHKD: 260,
    boxMarketHKD: 4100,
    packMarketHKD: 137,
    emoji: '∞',
    localImage: img.S3,
    fallbackImageUrl: tcgLogo('swsh3'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese infinite zone s3 booster box sealed'),
  },
  {
    id: 's4',
    nameJP: '仰天のボルテッカー',
    nameEN: 'Amazing Volt Tackle',
    series: 'Sword & Shield 系列',
    setCode: 'S4',
    releaseDate: '2020-10',
    packsPerBox: 30,
    packRetailJPY: 165,
    boxRetailJPY: 4950,
    packMarketUSD: 15.0,
    boxMarketUSD: 449,
    boxRetailHKD: 260,
    boxMarketHKD: 3500,
    packMarketHKD: 117,
    emoji: '⚡',
    localImage: img.S4,
    fallbackImageUrl: tcgLogo('swsh4'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese amazing volt tackle s4 booster box sealed'),
  },
  {
    id: 's5r',
    nameJP: '一撃マスター',
    nameEN: 'Single Strike Master',
    series: 'Sword & Shield 系列',
    setCode: 'S5R',
    releaseDate: '2021-01',
    packsPerBox: 30,
    packRetailJPY: 165,
    boxRetailJPY: 4950,
    packMarketUSD: 5.6,
    boxMarketUSD: 167,
    boxRetailHKD: 260,
    boxMarketHKD: 1300,
    packMarketHKD: 43,
    emoji: '👊',
    localImage: img.S5R,
    fallbackImageUrl: tcgLogo('swsh5'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese single strike master s5r booster box sealed'),
  },
  {
    id: 's5i',
    nameJP: '連撃マスター',
    nameEN: 'Rapid Strike Master',
    series: 'Sword & Shield 系列',
    setCode: 'S5I',
    releaseDate: '2021-01',
    packsPerBox: 30,
    packRetailJPY: 165,
    boxRetailJPY: 4950,
    packMarketUSD: 6.4,
    boxMarketUSD: 192,
    boxRetailHKD: 260,
    boxMarketHKD: 1500,
    packMarketHKD: 50,
    emoji: '🥊',
    localImage: img.S5I,
    fallbackImageUrl: tcgLogo('swsh5'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese rapid strike master s5i booster box sealed'),
  },
  {
    id: 's6a',
    nameJP: 'イーブイヒーローズ',
    nameEN: 'Eevee Heroes',
    series: 'Sword & Shield 系列',
    setCode: 'S6a',
    releaseDate: '2021-05',
    packsPerBox: 30,
    packRetailJPY: 165,
    boxRetailJPY: 4950,
    packMarketUSD: 32.1,
    boxMarketUSD: 962,
    boxRetailHKD: 260,
    boxMarketHKD: 7500,
    packMarketHKD: 250,
    emoji: '🦊',
    popular: true,
    localImage: img.S6a,
    fallbackImageUrl: tcgLogo('swsh6'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese eevee heroes s6a booster box sealed'),
  },
  {
    id: 's7r',
    nameJP: '蒼空ストリーム',
    nameEN: 'Blue Sky Stream',
    series: 'Sword & Shield 系列',
    setCode: 'S7R',
    releaseDate: '2021-07',
    packsPerBox: 30,
    packRetailJPY: 165,
    boxRetailJPY: 4950,
    packMarketUSD: 76.9,
    boxMarketUSD: 2308,
    boxRetailHKD: 260,
    boxMarketHKD: 18000,
    packMarketHKD: 600,
    emoji: '🌤️',
    popular: true,
    localImage: img.S7R,
    fallbackImageUrl: tcgLogo('swsh7'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese blue sky stream s7r booster box sealed'),
  },
  {
    id: 's7d',
    nameJP: '摩天パーフェクト',
    nameEN: 'Skyscraping Perfect',
    series: 'Sword & Shield 系列',
    setCode: 'S7D',
    releaseDate: '2021-07',
    packsPerBox: 30,
    packRetailJPY: 165,
    boxRetailJPY: 4950,
    packMarketUSD: 8.5,
    boxMarketUSD: 256,
    boxRetailHKD: 260,
    boxMarketHKD: 2000,
    packMarketHKD: 67,
    emoji: '🏙️',
    localImage: img.S7D,
    fallbackImageUrl: tcgLogo('swsh7'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese skyscraping perfect s7d booster box sealed'),
  },
  {
    id: 's8',
    nameJP: 'フュージョンアーツ',
    nameEN: 'Fusion Arts',
    series: 'Sword & Shield 系列',
    setCode: 'S8',
    releaseDate: '2021-10',
    packsPerBox: 30,
    packRetailJPY: 165,
    boxRetailJPY: 4950,
    packMarketUSD: 22.6,
    boxMarketUSD: 679,
    boxRetailHKD: 260,
    boxMarketHKD: 5300,
    packMarketHKD: 177,
    emoji: '⚗️',
    popular: true,
    localImage: img.S8,
    fallbackImageUrl: tcgLogo('swsh8'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese fusion arts s8 booster box sealed'),
  },
  {
    id: 's8b',
    nameJP: 'VMAXクライマックス',
    nameEN: 'VMAX Climax',
    series: 'Sword & Shield 系列',
    setCode: 'S8b',
    releaseDate: '2021-12',
    packsPerBox: 10,          // high-class pack
    packRetailJPY: 800,
    boxRetailJPY: 8000,
    packMarketUSD: 15.4,
    boxMarketUSD: 154,
    boxRetailHKD: 260,
    boxMarketHKD: 1200,
    packMarketHKD: 120,       // 1200 ÷ 10
    emoji: '🏆',
    popular: true,
    localImage: img.S8b,
    fallbackImageUrl: tcgLogo('swsh8'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese VMAX climax s8b booster box sealed'),
  },
  {
    id: 's9',
    nameJP: 'スターバース',
    nameEN: 'Star Birth',
    series: 'Sword & Shield 系列',
    setCode: 'S9',
    releaseDate: '2022-01',
    packsPerBox: 30,
    packRetailJPY: 165,
    boxRetailJPY: 4950,
    packMarketUSD: 6.4,
    boxMarketUSD: 192,
    boxRetailHKD: 260,
    boxMarketHKD: 1500,
    packMarketHKD: 50,
    emoji: '⭐',
    localImage: img.S9,
    fallbackImageUrl: tcgLogo('swsh9'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese star birth s9 booster box sealed'),
  },
  {
    id: 's9a',
    nameJP: 'バトルリージョン',
    nameEN: 'Battle Region',
    series: 'Sword & Shield 系列',
    setCode: 'S9a',
    releaseDate: '2022-03',
    packsPerBox: 30,
    packRetailJPY: 165,
    boxRetailJPY: 4950,
    packMarketUSD: 8.5,
    boxMarketUSD: 256,
    boxRetailHKD: 260,
    boxMarketHKD: 2000,
    packMarketHKD: 67,
    emoji: '🗺️',
    localImage: img.S9a,
    fallbackImageUrl: tcgLogo('swsh9'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese battle region s9a booster box sealed'),
  },
  {
    id: 's10a',
    nameJP: 'ダークファンタズマ',
    nameEN: 'Dark Phantasma',
    series: 'Sword & Shield 系列',
    setCode: 'S10a',
    releaseDate: '2022-05',
    packsPerBox: 30,
    packRetailJPY: 165,
    boxRetailJPY: 4950,
    packMarketUSD: 8.5,
    boxMarketUSD: 256,
    boxRetailHKD: 260,
    boxMarketHKD: 2000,
    packMarketHKD: 67,
    emoji: '👻',
    localImage: img.S10a,
    fallbackImageUrl: tcgLogo('swsh10'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese dark phantasma s10a booster box sealed'),
  },
  {
    id: 's10b',
    nameJP: 'Pokémon GO',
    nameEN: 'Pokemon GO',
    series: 'Sword & Shield 系列',
    setCode: 'S10b',
    releaseDate: '2022-06',
    packsPerBox: 30,
    packRetailJPY: 165,
    boxRetailJPY: 4950,
    packMarketUSD: 10.7,
    boxMarketUSD: 321,
    boxRetailHKD: 260,
    boxMarketHKD: 2500,
    packMarketHKD: 83,
    emoji: '📱',
    localImage: img.S10b,
    fallbackImageUrl: tcgLogo('swsh10'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese pokemon go s10b booster box sealed'),
  },
  {
    id: 's11',
    nameJP: 'ロストアビス',
    nameEN: 'Lost Abyss',
    series: 'Sword & Shield 系列',
    setCode: 'S11',
    releaseDate: '2022-07',
    packsPerBox: 30,
    packRetailJPY: 165,
    boxRetailJPY: 4950,
    packMarketUSD: 16.7,
    boxMarketUSD: 500,
    boxRetailHKD: 260,
    boxMarketHKD: 3900,
    packMarketHKD: 130,
    emoji: '🌀',
    popular: true,
    localImage: img.S11,
    fallbackImageUrl: tcgLogo('swsh11'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese lost abyss s11 booster box sealed'),
  },
  {
    id: 's12',
    nameJP: 'パラダイムトリガー',
    nameEN: 'Paradigm Trigger',
    series: 'Sword & Shield 系列',
    setCode: 'S12',
    releaseDate: '2022-09',
    packsPerBox: 30,
    packRetailJPY: 165,
    boxRetailJPY: 4950,
    packMarketUSD: 7.7,
    boxMarketUSD: 231,
    boxRetailHKD: 260,
    boxMarketHKD: 1800,
    packMarketHKD: 60,
    emoji: '🔭',
    localImage: img.S12,
    fallbackImageUrl: tcgLogo('swsh12'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese paradigm trigger s12 booster box sealed'),
  },
  {
    id: 's12a',
    nameJP: 'VSTARユニバース',
    nameEN: 'VSTAR Universe',
    series: 'Sword & Shield 系列',
    setCode: 'S12a',
    releaseDate: '2022-10',
    packsPerBox: 10,          // high-class pack
    packRetailJPY: 880,
    boxRetailJPY: 8800,
    packMarketUSD: 31.4,
    boxMarketUSD: 314,
    boxRetailHKD: 260,
    boxMarketHKD: 2450,
    packMarketHKD: 245,       // 2450 ÷ 10
    emoji: '🌌',
    popular: true,
    localImage: img.S12a,
    fallbackImageUrl: tcgLogo('swsh12'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese VSTAR universe s12a booster box sealed'),
  },
  {
    id: 'sp',
    nameJP: '25周年記念コレクション',
    nameEN: '25th Anniversary Collection',
    series: 'Sword & Shield 系列',
    setCode: 'SP',
    releaseDate: '2021-10',
    packsPerBox: 20,          // anniversary set
    packRetailJPY: 550,
    boxRetailJPY: 11000,
    packMarketUSD: 21.8,
    boxMarketUSD: 436,
    boxRetailHKD: 260,
    boxMarketHKD: 3400,
    packMarketHKD: 170,       // 3400 ÷ 20
    emoji: '🎂',
    popular: true,
    localImage: img.SP,
    fallbackImageUrl: tcgLogo('cel25'),
    pricechartingId: null,
    ebayUrl: ebay('pokemon japanese 25th anniversary collection SP booster box sealed'),
  },
];
