/**
 * Traditional Chinese (HK/TW) Pokémon name → English name mapping
 * Used to support Chinese-language search in the Search screen.
 * Keys are normalised to lowercase for case-insensitive matching.
 */
export const ZH_POKEMON_MAP: Record<string, string> = {
  // Gen 1
  '比卡超': 'Pikachu',
  '皮卡丘': 'Pikachu',
  '噴火龍': 'Charizard',
  '超夢': 'Mewtwo',
  '夢幻': 'Mew',
  '伊布': 'Eevee',
  '水伊布': 'Vaporeon',
  '雷伊布': 'Jolteon',
  '火伊布': 'Flareon',
  '耿鬼': 'Gengar',
  '快龍': 'Dragonite',
  '化石翼龍': 'Aerodactyl',
  '卡比獸': 'Snorlax',
  '喵喵': 'Meowth',
  '傑尼龜': 'Squirtle',
  '小火龍': 'Charmander',
  '妙蛙種子': 'Bulbasaur',
  '雙刀': 'Scyther',
  '電擊獸': 'Raichu',
  '水箭龜': 'Blastoise',
  '妙蛙花': 'Venusaur',
  '李察': 'Rhydon',
  '三地鼠': 'Dugtrio',
  '地鼠': 'Diglett',
  '喇叭芽': 'Bellsprout',
  '君主蛇': 'Arbok',
  '暴鯉龍': 'Gyarados',
  '乘龍': 'Dragonair',
  '迷你龍': 'Dratini',
  '小磁怪': 'Magnemite',
  '磁怪': 'Magneton',
  '霸力龍': 'Machamp',
  '火爆獸': 'Arcanine',
  '風速狗': 'Growlithe',
  '百變怪': 'Ditto',
  // Gen 2
  '黃金鴨': 'Psyduck',
  '神奇鴨': 'Golduck',
  '幸福蛋': 'Chansey',
  '皮皮': 'Jigglypuff',
  '胖丁': 'Jigglypuff',
  '甲殼忍者': 'Blastoise',
  '月亮伊布': 'Umbreon',
  '太陽伊布': 'Espeon',
  '月精靈': 'Umbreon',
  '太陽精靈': 'Espeon',
  '葉精靈': 'Leafeon',
  '冰精靈': 'Glaceon',
  '仙子伊布': 'Sylveon',
  '閃電鳥': 'Zapdos',
  '急凍鳥': 'Articuno',
  '火焰鳥': 'Moltres',
  '聖火駒': 'Ho-Oh',
  '虹翼': 'Ho-Oh',
  '路基歐': 'Lugia',
  '神獸盧基亞': 'Lugia',
  '大針蜂': 'Beedrill',
  '喇叭花怪': 'Victreebel',
  // Gen 3
  '夢幻球': 'Jirachi',
  '基拉祈': 'Jirachi',
  '雷克多拉': 'Rayquaza',
  '藍海獅': 'Kyogre',
  '固拉多': 'Groudon',
  '晴天娃娃': 'Castform',
  '沙奈朵': 'Gardevoir',
  '沙漠蜥蜴': 'Flygon',
  '水梅': 'Milotic',
  '美纖龍': 'Milotic',
  // Gen 4
  '帝牙海獅': 'Empoleon',
  '骷髏龍': 'Garchomp',
  '快快糰子': 'Riolu',
  '路卡利歐': 'Lucario',
  '球球海獅': 'Piplup',
  '小福蛋': 'Happiny',
  '煤煤蟲': 'Budew',
  '甜心糰子': 'Togekiss',
  '帕路奇亞': 'Palkia',
  '帝亞盧加': 'Dialga',
  '騎拉帝納': 'Giratina',
  '阿爾宙斯': 'Arceus',
  '席多藍恩': 'Cresselia',
  '達克萊伊': 'Darkrai',
  // Gen 5
  '黑色雷可賽暗': 'Zekrom',
  '雷卡姆': 'Reshiram',
  '白雷卡姆': 'Reshiram',
  'Z1': 'Zekrom',
  '達蘭玄玄冰': 'Kyurem',
  // Gen 6
  '哲爾尼亞斯': 'Xerneas',
  '伊裴爾塔爾': 'Yveltal',
  '基格爾德': 'Zygarde',
  // Gen 7
  '日月惡鯊': 'Incineroar',
  '阿羅拉九尾': 'Alolan Ninetales',
  '卡璞·鳶鳶': 'Tapu Koko',
  '卡璞·蝶蝶': 'Tapu Lele',
  '露奈雅拉': 'Lunala',
  '索爾迦雷歐': 'Solgaleo',
  '瑪圖利斯': 'Marshadow',
  '奈路奇': 'Naganadel',
  // Gen 8 / Sword & Shield
  '蒼響': 'Zacian',
  '藏瑪然特': 'Zamazenta',
  '穆可寇煤': 'Eternatus',
  '藍染鶴奇': 'Calyrex',
  // Gen 9 / Scarlet & Violet
  '柯利亞': 'Koraidon',
  '密萊坦': 'Miraidon',
  '沼電龍': 'Quaquaval',
  '暴鈦龍': 'Tyranitar',
  // Common abbreviations / alternate names
  '比卡': 'Pikachu',
  '超夢二': 'Mewtwo',
  '大噴火': 'Charizard',
};

/**
 * Japanese katakana Pokémon name → English name mapping
 * Used for OCR camera scan of Japanese cards.
 */
export const JP_POKEMON_MAP: Record<string, string> = {
  // Gen 1
  'ピカチュウ': 'Pikachu',
  'ライチュウ': 'Raichu',
  'リザードン': 'Charizard',
  'リザード': 'Charmeleon',
  'ヒトカゲ': 'Charmander',
  'フシギバナ': 'Venusaur',
  'フシギソウ': 'Ivysaur',
  'フシギダネ': 'Bulbasaur',
  'カメックス': 'Blastoise',
  'カメール': 'Wartortle',
  'ゼニガメ': 'Squirtle',
  'ミュウツー': 'Mewtwo',
  'ミュウ': 'Mew',
  'イーブイ': 'Eevee',
  'シャワーズ': 'Vaporeon',
  'サンダース': 'Jolteon',
  'ブースター': 'Flareon',
  'ゲンガー': 'Gengar',
  'ゴース': 'Gastly',
  'ゴースト': 'Haunter',
  'カビゴン': 'Snorlax',
  'ラプラス': 'Lapras',
  'カイリュー': 'Dragonite',
  'ハクリュー': 'Dragonair',
  'ミニリュウ': 'Dratini',
  'ヤドラン': 'Slowbro',
  'ヤドン': 'Slowpoke',
  'ニャース': 'Meowth',
  'ヒトデマン': 'Staryu',
  'スターミー': 'Starmie',
  'バリヤード': 'Mr. Mime',
  'サワムラー': 'Hitmonlee',
  'エビワラー': 'Hitmonchan',
  'ルージュラ': 'Jynx',
  'エレブー': 'Electabuzz',
  'ブーバー': 'Magmar',
  'ケンタロス': 'Tauros',
  'プテラ': 'Aerodactyl',
  'ナッシー': 'Exeggutor',
  'ガルーラ': 'Kangaskhan',
  'タマタマ': 'Exeggcute',
  'ストライク': 'Scyther',
  'レアコイル': 'Magneton',
  'コイル': 'Magnemite',
  'カイロス': 'Pinsir',
  'ベトベトン': 'Muk',
  // Gen 2
  'ルギア': 'Lugia',
  'ホウオウ': 'Ho-Oh',
  'セレビィ': 'Celebi',
  'エンテイ': 'Entei',
  'スイクン': 'Suicune',
  'ライコウ': 'Raikou',
  'ブラッキー': 'Umbreon',
  'エーフィ': 'Espeon',
  'バンギラス': 'Tyranitar',
  'ハピナス': 'Blissey',
  'ツボツボ': 'Shuckle',
  'ハガネール': 'Steelix',
  'ヘルガー': 'Houndoom',
  'ヘラクロス': 'Heracross',
  'ミロカロス': 'Milotic',
  'ワタッコ': 'Jumpluff',
  // Gen 3
  'レックウザ': 'Rayquaza',
  'カイオーガ': 'Kyogre',
  'グラードン': 'Groudon',
  'ジラーチ': 'Jirachi',
  'デオキシス': 'Deoxys',
  'メタグロス': 'Metagross',
  'サーナイト': 'Gardevoir',
  'キルリア': 'Kirlia',
  'ラルトス': 'Ralts',
  'フライゴン': 'Flygon',
  'ボーマンダ': 'Salamence',
  'ラティアス': 'Latias',
  'ラティオス': 'Latios',
  // Gen 4
  'ルカリオ': 'Lucario',
  'リオル': 'Riolu',
  'ガブリアス': 'Garchomp',
  'フカマル': 'Gible',
  'ディアルガ': 'Dialga',
  'パルキア': 'Palkia',
  'ギラティナ': 'Giratina',
  'アルセウス': 'Arceus',
  'ダークライ': 'Darkrai',
  'シェイミ': 'Shaymin',
  'ヒードラン': 'Heatran',
  'クレセリア': 'Cresselia',
  'ゾロアーク': 'Zoroark',
  'ゾロア': 'Zorua',
  'ゴウカザル': 'Infernape',
  'エンペルト': 'Empoleon',
  'ポッチャマ': 'Piplup',
  'ニンフィア': 'Sylveon',
  'リーフィア': 'Leafeon',
  'グレイシア': 'Glaceon',
  // Gen 5
  'ゼクロム': 'Zekrom',
  'レシラム': 'Reshiram',
  'キュレム': 'Kyurem',
  'ゲノセクト': 'Genesect',
  'ビクティニ': 'Victini',
  'サザンドラ': 'Hydreigon',
  'シャンデラ': 'Chandelure',
  // Gen 6
  'ゼルネアス': 'Xerneas',
  'イベルタル': 'Yveltal',
  'ジガルデ': 'Zygarde',
  'ディアンシー': 'Diancie',
  'フーパ': 'Hoopa',
  'ボルケニオン': 'Volcanion',
  'ゲッコウガ': 'Greninja',
  'ハリマロン': 'Chespin',
  // Gen 7
  'ソルガレオ': 'Solgaleo',
  'ルナアーラ': 'Lunala',
  'ネクロズマ': 'Necrozma',
  'マーシャドー': 'Marshadow',
  'カプ・コケコ': 'Tapu Koko',
  'カプ・テテフ': 'Tapu Lele',
  'カプ・ブルル': 'Tapu Bulu',
  'カプ・レヒレ': 'Tapu Fini',
  'イワンコ': 'Rockruff',
  'ルガルガン': 'Lycanroc',
  'アローラキュウコン': 'Alolan Ninetales',
  'カプコケコ': 'Tapu Koko',
  // Gen 8
  'ザシアン': 'Zacian',
  'ザマゼンタ': 'Zamazenta',
  'ムゲンダイナ': 'Eternatus',
  'バドレックス': 'Calyrex',
  'ドラパルト': 'Dragapult',
  'ヒスイゾロアーク': 'Hisuian Zoroark',
  'ヒスイゾロア': 'Hisuian Zorua',
  // Gen 9 / Scarlet & Violet (most popular for collectors)
  'コライドン': 'Koraidon',
  'ミライドン': 'Miraidon',
  'ハバタクカミ': 'Flutter Mane',
  'テツノカイナ': 'Iron Hands',
  'テツノブジン': 'Iron Valiant',
  'テツノドクガ': 'Iron Moth',
  'テツノワダチ': 'Iron Treads',
  'テツノイサハ': 'Iron Thorns',
  'パオジアン': 'Chien-Pao',
  'チオンジェン': 'Wo-Chien',
  'イイネイヌ': 'Chi-Yu',
  'サケブシッポ': 'Scream Tail',
  'アラブルタケ': 'Brute Bonnet',
  'タケルライコ': 'Raging Bolt',
  'ゴーゴート': 'Gogoat',
  'マスカーニャ': 'Meowscarada',
  'ウェーニバル': 'Quaquaval',
  'ラウドボーン': 'Skeledirge',
  'ニャオハ': 'Sprigatito',
  'クワッス': 'Quaxly',
  'ホゲータ': 'Fuecoco',
  'テラパゴス': 'Terapagos',
  'オーガポン': 'Ogerpon',
  'ペパー': 'Pepper',
  'イキリンコ': 'Squawkabilly',
  'アノホラグサ': 'Toedscool',
  'リキキリン': 'Farigiraf',
  'ナミイルカ': 'Finizen',
  'マナフィ': 'Manaphy',
  // Commonly scanned / high value
  'ミミッキュ': 'Mimikyu',
  'フェローチェ': 'Buzzwole',
  'テッカグヤ': 'Celesteela',
  'カートゥーン': 'Kartana',
};

/**
 * Given a user query string, detect if it contains Chinese or Japanese Pokémon name(s)
 * and return the English equivalent to use in the API search.
 * Returns the original string if no match found.
 */
export function normalizeQuery(input: string): string {
  const trimmed = input.trim();

  // Check Japanese katakana map first (for OCR scans of JP cards)
  if (JP_POKEMON_MAP[trimmed]) return JP_POKEMON_MAP[trimmed];
  for (const [jp, en] of Object.entries(JP_POKEMON_MAP)) {
    if (trimmed.includes(jp)) return en;
  }

  // Check Traditional Chinese map
  if (ZH_POKEMON_MAP[trimmed]) return ZH_POKEMON_MAP[trimmed];
  for (const [zh, en] of Object.entries(ZH_POKEMON_MAP)) {
    if (trimmed.includes(zh)) return en;
  }

  return trimmed;
}
